export const FETCHACCOMMODATIONS = 'FETCHACCOMMODATIONS';
export const FETCH_ACCOMMODATIONS_PENDING = 'FETCH_ACCOMMODATIONS_PENDING';
export const FETCH_ACCOMMODATIONS_SUCCESS = 'FETCH_ACCOMMODATIONS_SUCCESS';
export const FETCH_ACCOMMODATIONS_FAILED = 'FETCH_ACCOMMODATIONS_FAILED';

export const CREATE_ACCOMMODATION_PENDING = 'CREATE_ACCOMMODATION_PENDING ';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_FAILED = 'CREATE_ACCOMMODATION_FAILED';

export const FETCH_SINGLE_ACCOMMODATION_PENDING =
  'FETCH_SINGLE_ACCOMMODATION_PENDING';
export const FETCH_SINGLE_ACCOMMODATION_SUCCESS =
  'FETCH_SINGLE_ACCOMMODATION_SUCCESS';
export const FETCH_SINGLE_ACCOMMODATION_FAILED =
  'FETCH_SINGLE_ACCOMMODATION_FAILED';

export const DELETE_ACCOMMODATION_PENDING = 'DELETE_ACCOMMODATION_PENDING';
export const DELETE_ACCOMMODATION_SUCCESS = 'DELETE_ACCOMMODATION_SUCCESS';
export const DELETE_ACCOMMODATION_FAILED = 'DELETE_ACCOMMODATION_FAILED';

export const UPDATE_ACCOMMODATION_PENDING = 'UPDATE_ACCOMMODATION_PENDING';
export const UPDATE_ACCOMMODATION_SUCCESS = 'UPDATE_ACCOMMODATION_SUCCESS';
export const UPDATE_ACCOMMODATION_FAILED = 'UPDATE_ACCOMMODATION_FAILED';

export const FILTER_ACCOMMODATION = 'FILTER_ACCOMMODATION';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';

export const LIKE_ACCOMMODATION = 'LIKE_ACCOMMODATION';
export const LIKE_ACCOMMODATION_FAILED = 'LIKE_ACCOMMODATION_FAILED';
