export const FETCH_ALL_BOOKINGS_PENDING = 'FETCH_ALL_BOOKINGS_PENDING';
export const FETCH_ALL_BOOKINGS_SUCCESS = 'FETCH_ALL_BOOKINGS_SUCCESS';
export const FETCH_ALL_BOOKINGS_FAILED = 'FETCH_ALL_BOOKINGS_FAILED';
export const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED';

export const FETCH_USER_BOOKINGS_PENDING = 'FETCH_USER_BOOKINGS_PENDING';
export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAILED = 'FETCH_USER_BOOKINGS_FAILED';

export const UPDATE_BOOKING_PENDING = 'UPDATE_BOOKING_PENDING';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILED = 'UPDATE_BOOKING_FAILED';

export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILED = 'DELETE_BOOKING_FAILED';
