export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ERR_GETTING_LOCATIONS = 'ERR_GETTING_LOCATIONS';
export const GETLOCATIONS = 'GETLOCATIONS';
export const GET_ONE_LOCATION = 'GET_ONE_LOCATION';
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
