export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_SINGLE_NOTIFICATION = 'FETCH_SINGLE_NOTIFICATION';
export const MARK_ALL_NOTIFICATIONS = 'MARK_ALL_NOTIFICATIONS';
export const MARK_SINGLE_NOTIFICATION = 'MARK_SINGLE_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
