export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RETRIEVE_PROFILE = 'RETRIEVE_PROFILE';
export const RETRIEVING_ERROR = 'RETRIEVING_ERROR';
export const UPDATING_ERROR = 'UPDATING_ERROR';
