/* eslint-disable import/prefer-default-export */
export const FETCH_REQUESTS_PENDING = 'FETCH_REQUESTS_PENDING';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_ERROR = 'FETCH_REQUESTS_ERROR';
export const DELETE_REQUESTS_SUCCESS = 'DELETE_REQUESTS_SUCCESS';
export const DELETE_REQUESTS_ERROR = 'DELETE_REQUESTS_ERROR';
export const DELETE_REQUESTS_PENDING = 'DELETE_REQUESTS_PENDING';
export const APPROVE_PENDING_REQUEST = 'APPROVE_PENDING_REQUEST';
export const APPROVE_REQUEST_SUCCESS = 'APPROVE_REQUEST_SUCCESS';
export const APPROVE_REQUEST_ERROR = 'APPROVE_REQUEST_ERROR';
export const REJECT_REQUEST_ERROR = 'REJECT_REQUEST_ERROR';
export const REJECT_REQUEST_SUCCESS = 'REJECT_REQUEST_SUCCESS';
export const REJECT_PENDING_REQUEST = 'REJECT_PENDING_REQUEST';

export const CREATETRIP = 'CREATETRIP';
export const CREATETRIP_FAILED = 'CREATETRIP_FAILED';
export const CREATETRIP_SUCCESS = 'CREATETRIP_SUCCESS';

export const UPDATETRIP = 'UPDATETRIP';
export const UPDATERIP_FAILED = 'UPDATETRIP_FAILED';
export const UPDATETRIP_SUCCESS = 'UPDATETRIP_SUCCESS';
