export const CREATE_ROOM_PENDING = 'CREATE_ROOM_PENDING';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';

export const FETCH_ROOM_PENDING = 'FETCH_ROOM_PENDING';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_FAILED = 'FETCH_ROOM_FAILED';
