export const RETRIEVED_TRIP_COMMENT = 'RETRIEVED_TRIP_COMMENT';
export const RETRIEVED_MORE_TRIP_COMMENT = 'RETRIEVED_MORE_TRIP_COMMENT';
export const EDIT_TRIP_COMMENT = 'EDIT_TRIP_COMMENT';
export const CREATE_TRIP_COMMENT = 'CREATE_TRIP_COMMENT';

export const LOADING_TRIP_COMMENT = 'LOADING_TRIP_COMMENT';
export const LOADING_MORE_TRIP_COMMENT = 'LOADING_MORE_TRIP_COMMENT';
export const LOADING_DELETE_TRIP_COMMENT = 'LOADING_DELETE_TRIP_COMMENT';
export const LOADING_EDIT_TRIP_COMMENT = 'LOADING_EDIT_TRIP_COMMENT';
export const LOADING_CREATE_TRIP_COMMENT = 'LOADING_CREATE_TRIP_COMMENT';

export const ERROR_TRIP_COMMENT = 'ERROR_TRIP_COMMENT';
