export const ASSIGNROLE = 'ASSIGN_ROLE';
export const GETALLROLES = 'GET_ALL_ROLES';
export const ASSIGNROLEERROR = 'ASSIGNROLEERROR';
export const GETUSERS = 'GETUSERS';
export const GET_DETAILED = 'GET_DETAILED';
export const ASSIGN_MANAGER = 'ASSIGN_MANAGER';
